package olas.pojo;
// Generated Apr 24, 2019 11:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {


    private String email;
    private String firstName;
    private String lastName;
    private String passwords;
    private String phone;
    private String position;
    private String createdDate;
    private int id;
    private Boolean status;

    public Employees() {
    }


    public Employees(String email) {
        this.email = email;
    }


    public Employees(String email, String firstName, String lastName, String passwords, String phone, String position, int id, Boolean status, String createdDate) {
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.passwords = passwords;
        this.phone = phone;
        this.position = position;
        this.createdDate = createdDate;
        this.id = id;
        this.status = status;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPasswords() {
        return this.passwords;
    }

    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }


}


