package olas.pojo;
// Generated Apr 24, 2019 11:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplies generated by hbm2java
 */
public class Supplies  implements java.io.Serializable {


     private String itemCode;
     private Employees employees;
     private String itemName;
     private String itemType;
     private String supplyName;
     private String supplyEmail;
     private String supplyPhone;
     private Double unitPrice;
     private Integer quantity;
     private Double totalPrice;
     private String manufacturedDate;
     private String expireDate;
     private String receiveDate;
     private String createdDate;
     private Set usageses = new HashSet(0);

    public Supplies() {
    }

	
    public Supplies(String itemCode) {
        this.itemCode = itemCode;
    }
    public Supplies(String itemCode, Employees employees, String itemName, String itemType, String supplyName, String supplyEmail, String supplyPhone, Double unitPrice, Integer quantity, Double totalPrice, String manufacturedDate, String expireDate, String receiveDate, String createdDate, Set usageses) {
       this.itemCode = itemCode;
       this.employees = employees;
       this.itemName = itemName;
       this.itemType = itemType;
       this.supplyName = supplyName;
       this.supplyEmail = supplyEmail;
       this.supplyPhone = supplyPhone;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.totalPrice = totalPrice;
       this.manufacturedDate = manufacturedDate;
       this.expireDate = expireDate;
       this.receiveDate = receiveDate;
       this.createdDate = createdDate;
       this.usageses = usageses;
    }
   
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
    public String getSupplyName() {
        return this.supplyName;
    }
    
    public void setSupplyName(String supplyName) {
        this.supplyName = supplyName;
    }
    public String getSupplyEmail() {
        return this.supplyEmail;
    }
    
    public void setSupplyEmail(String supplyEmail) {
        this.supplyEmail = supplyEmail;
    }
    public String getSupplyPhone() {
        return this.supplyPhone;
    }
    
    public void setSupplyPhone(String supplyPhone) {
        this.supplyPhone = supplyPhone;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getManufacturedDate() {
        return this.manufacturedDate;
    }
    
    public void setManufacturedDate(String manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }
    public String getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }
    public String getReceiveDate() {
        return this.receiveDate;
    }
    
    public void setReceiveDate(String receiveDate) {
        this.receiveDate = receiveDate;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public Set getUsageses() {
        return this.usageses;
    }
    
    public void setUsageses(Set usageses) {
        this.usageses = usageses;
    }




}


